var COMMANDS  = { "en" : {
  "voice" : "UK English Female",
  "default" : 'Say "What can I say?" to see a list of commands...',
  "hi" : 'Hi, sexy!',
  "whois" : "Who are you?",
  "whatcanisay" : 'What can I say',
  "home" : 'Go home',
  "sleep" : 'Go to sleep',
  "wake" : 'Wake up',
  "debug" : 'Show debug information',
  "map" : 'Show map',
  "locaiton" : 'Show (me a) map of *location',
  "zoomin" : '(map) zoom in',
  "zoomout" : '(map) zoom out',
  "zoomvalue" : '(map) zoom (to) *value',
  "zoomreset" : '(map) reset zoom',
  "playyoutube" : 'play *term youtube',
  "ytbplaylist" : '*term playlist',
  "stopyoutube" : 'stop youtube',
  "subway" : 'show me *linenumber info at *station',
  "musicplay" : "play music",
  "musicstop" : "stop music",
  "info" :  "Here is a list of commands...",
  "news" : "Show me news",
  "photo" : "Take a photo",
  "video" : "Take a video",
  "lighton" : "Light on",
  "lightoff" : "Light off"
},
  "ko" : {
    "voice" : "Korean Female",
    "default" : '"메뉴"라고 말해 보세요',
    "hi" : '안녕 정출',
    "whatcanisay" : '메뉴',
    "whois" : "너는 누구니",
    "home" : '홈으로',
    "sleep" : '잘자 미러',
    "wake" : '안녕 미러',
    "debug" : '디버그',
    "map" : '지금 어디 야',
    "locaiton" : '*location위치 보여 줘',
    "zoomin" : '지도 확대',
    "zoomout" : '지도 축소',
    "zoomvalue" : '*value값으로지도 설정',
    "zoomreset" : '지도 리셋',
    "playyoutube" : '*term 동영상 (재생)(켜 줘)(플레이)(틀어 줘)(보여 줘)',
    "ytbplaylist" : '*term 플레이어 (재생)(켜 줘)(플레이)(틀어 줘)(보여 줘)',
    "stopyoutube" : '동영상 (꺼 봐)(꺼 줘)(정지)(중지)(그만)(꺼져)',
    "subway" : '*station역 *linenumber(호)선 *updown',
    "musicplay" : "음악 (재생)(켜 줘)",
    "musicstop" : "음악 (꺼 봐)(꺼 줘)(정지)(중지)(꺼져)",
    "info" : "다음은 사용 가능한 질문입니다",
    "news" : "뉴스 보여 줘",
    "photo" : "사진 촬영",
    "video" : "비디오 촬영",
	"lighton" : "불 켜",
	"lightoff" : "불 꺼"
  }
};
